[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

# Note: Removed environment variable overrides to let Railway handle networking automatically
# The Procfile will handle the server binding with dynamic $PORT variable 